---
- name: Installed shared k8s resources
  hosts: server
  become: true
  
  pre_tasks:
    - name: Get running services
      service_facts:

    - name: Make sure pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Make sure python dependencies are installed on server
      pip:
        name:
          - openshift
          - pyyaml

  tasks:
    - name: See if Helm is installed
      stat:
        path: "/usr/local/bin/helm"
      register: helm_binary

    - name: What is helm_binary
      debug:
        msg: "{{ helm_binary }}"

    - name: Install Helm on the server node
      shell: 'curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash'
      when: not helm_binary.stat.exists

    - name: Download cert-manager manifest
      ansible.builtin.get_url:
        url: https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml
        dest: ~/cert-manager.yaml
        mode: '0664'

    - name: Install cert-manager
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        state: present
        src: ~/cert-manager.yaml

    - name: Add Longhorn helm repo
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: "https://charts.longhorn.io"

    - name: Install Longhorn
      kubernetes.core.helm:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        update_repo_cache: true
        name: longhorn
        chart_ref: longhorn/longhorn
        release_namespace: longhorn-system
        create_namespace: true
        values:
          nodeDownPodDeletionPolicy: delete-deployment-pod

###### WIP Adding Prometheus

    # - name: Add Prometheus Helm chart repository
    #   kubernetes.core.helm_repository:
    #     name: prometheus-community
    #     repo_url: "https://prometheus-community.github.io/helm-charts"
      
    # - name: Install Prometheus stack
    #   kubernetes.core.helm:
    #     kubeconfig: /etc/rancher/k3s/k3s.yaml
    #     update_repo_cache: true
    #     name: prometheus
    #     chart_ref: prometheus-community/kube-prometheus-stack
    #     release_namespace: monitoring
    #     create_namespace: true
    
    # - name: Download Prometheus Operator
    #   ansible.builtin.get_url:
    #     url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/bundle.yaml
    #     dest: /home/ubuntu/prometheus_bundle.yaml
    #     mode: '0664'

    # - name: Change Prometheus bundle namespace
    #   ansible.builtin.replace:
    #     path: /home/ubuntu/prometheus_bundle.yaml
    #     regexp: '^\s*namespace: default$'
    #     replace: 'namespace: monitoring'

    # - name: Create 'monitoring' namespace
    #   kubernetes.core.k8s:
    #     kubeconfig: /etc/rancher/k3s/k3s.yaml
    #     name: monitoring
    #     kind: Namespace
    #     state: present

    # - name: Install Prometheus Operator
    #   kubernetes.core.k8s:
    #     kubeconfig: /etc/rancher/k3s/k3s.yaml
    #     state: present
    #     src: ~/prometheus_bundle.yaml