# ---
# - hosts: all

#   tasks:
#     - name: Print all available facts
#       ansible.builtin.debug:
#         var: ansible_facts['eth0']['ipv4']['address']
    
#     - name: Test netplan config template
#       template: 
#         src: templates/01-netcfg.j2
#         dest: ~/01-netcfg-deleteme.yml

# ---
# - name: Rpi Configuration
#   hosts: all
#   become: true

#   handlers:
#     - name: reboot required
#       reboot:

#   tasks:
#     - name: Configure POE HAT fan speeds
#       template:
#         src: templates/50-rpi-fan.rules.j2
#         dest: /etc/udev/rules.d/50-rpi-fan.rules
#       notify: reboot required

# ---
# - name: test get k3s token
#   hosts: server
#   become: true

#   tasks:
#     - name: get k3s token
#       slurp:
#         src: /var/lib/rancher/k3s/server/node-token
#       register: k3s_token
    
#     - name: Print k3s_token
#       debug:
#         msg: "{{ k3s_token['content'] | b64decode }}"

# - name: print k3s token from test
#   hosts: agent
#   become: true

#   vars_files:
#     - vars.yml

#   tasks:
#     - name: print k3s token
#       debug:
#         msg: "{{ hostvars[k3s_token_server]['k3s_token']['content'] | b64decode }}"

---
- name: Test check k3s.service
  hosts: server
  become: true

  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    # - name: Check for service
    #   debug:
    #     var: ansible_facts.services['testing.service']
    #   register: k3s_service

    - name: debug test
      debug:
        msg: "testing.service is not here"
      when: "'testing.service' not in services"