---
- name: Get running services
  service_facts:

- name: Allow K8s API server connections
  community.general.ufw:
    rule: allow
    port: 6443
    proto: tcp
  notify: Reload firewall

- name: Allow HTTP connections
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp
  notify: Reload firewall

- name: Allow HTTPS connections
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp
  notify: Reload firewall

- name: Register taint fact
  set_fact:
    node_taint: "--node-taint k3s-type=server:PreferNoSchedule"
  when: taint

- name: Do not use taint
  set_fact:
    node_taint: ""
  when: not taint

- name: Install K3s server
  shell: 'curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s - --disable traefik --disable local-storage {{ node_taint }}'
  when: "'k3s.service' not in services"

- name: Get K3s Token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token
