---
- name: Get running services
  service_facts:

- name: Install initial K3s HA server
  shell: 'curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --cluster-init --disable traefik --disable local-storage" K3S_TOKEN={{ k3s_token }} K3S_KUBECONFIG_MODE="644" sh -s -'
  when: "'k3s.service' not in services"

# - name: Get K3s Token
#   slurp:
#     src: /var/lib/rancher/k3s/server/node-token
#   register: k3s_token
